//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ZKAccessEntitiesforabsence3 : DbContext
    {
        public ZKAccessEntitiesforabsence3()
            : base("name=ZKAccessEntitiesforabsence3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<absencev> absencevs { get; set; }
    
        public virtual ObjectResult<absence_Result> absence(string the_input_date1, string the_input_date2, string dept)
        {
            var the_input_date1Parameter = the_input_date1 != null ?
                new ObjectParameter("the_input_date1", the_input_date1) :
                new ObjectParameter("the_input_date1", typeof(string));
    
            var the_input_date2Parameter = the_input_date2 != null ?
                new ObjectParameter("the_input_date2", the_input_date2) :
                new ObjectParameter("the_input_date2", typeof(string));
    
            var deptParameter = dept != null ?
                new ObjectParameter("dept", dept) :
                new ObjectParameter("dept", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<absence_Result>("absence", the_input_date1Parameter, the_input_date2Parameter, deptParameter);
        }
    
        public virtual ObjectResult<absencev> absencesp(string the_input_date1, string the_input_date2, string dept)
        {
            var the_input_date1Parameter = the_input_date1 != null ?
                new ObjectParameter("the_input_date1", the_input_date1) :
                new ObjectParameter("the_input_date1", typeof(string));
    
            var the_input_date2Parameter = the_input_date2 != null ?
                new ObjectParameter("the_input_date2", the_input_date2) :
                new ObjectParameter("the_input_date2", typeof(string));
    
            var deptParameter = dept != null ?
                new ObjectParameter("dept", dept) :
                new ObjectParameter("dept", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<absencev>("absencesp", the_input_date1Parameter, the_input_date2Parameter, deptParameter);
        }
    
        public virtual ObjectResult<absencev> absencesp(string the_input_date1, string the_input_date2, string dept, MergeOption mergeOption)
        {
            var the_input_date1Parameter = the_input_date1 != null ?
                new ObjectParameter("the_input_date1", the_input_date1) :
                new ObjectParameter("the_input_date1", typeof(string));
    
            var the_input_date2Parameter = the_input_date2 != null ?
                new ObjectParameter("the_input_date2", the_input_date2) :
                new ObjectParameter("the_input_date2", typeof(string));
    
            var deptParameter = dept != null ?
                new ObjectParameter("dept", dept) :
                new ObjectParameter("dept", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<absencev>("absencesp", mergeOption, the_input_date1Parameter, the_input_date2Parameter, deptParameter);
        }
    }
}
