//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendancev
    {
        public string atttime { get; set; }
        public string device_name { get; set; }
        public string Name { get; set; }
        public string Badgenumber { get; set; }
        public string DEPTNAME { get; set; }
        public Nullable<int> DEFAULTDEPTID { get; set; }
        public string Expr1 { get; set; }
        public int DEPTID { get; set; }
        public int id { get; set; }
        public string thedate { get; set; }
        public Nullable<System.TimeSpan> thetime { get; set; }
    }
}
