//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cumlative
    {
        public long id { get; set; }
        public string pin { get; set; }
        public Nullable<int> delayinmin { get; set; }
        public string themonth { get; set; }
        public string theyear { get; set; }
        public string DEPTNAME { get; set; }
        public string Name { get; set; }
    }
}
