//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class othrZKAccessEntities4 : DbContext
    {
        public othrZKAccessEntities4()
            : base("name=othrZKAccessEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<othert> otherts { get; set; }
    
        public virtual ObjectResult<getothers_Result> getothers(string the_inputdate)
        {
            var the_inputdateParameter = the_inputdate != null ?
                new ObjectParameter("the_inputdate", the_inputdate) :
                new ObjectParameter("the_inputdate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getothers_Result>("getothers", the_inputdateParameter);
        }
    
        public virtual ObjectResult<othert> getoth(string the_inputdate)
        {
            var the_inputdateParameter = the_inputdate != null ?
                new ObjectParameter("the_inputdate", the_inputdate) :
                new ObjectParameter("the_inputdate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<othert>("getoth", the_inputdateParameter);
        }
    
        public virtual ObjectResult<othert> getoth(string the_inputdate, MergeOption mergeOption)
        {
            var the_inputdateParameter = the_inputdate != null ?
                new ObjectParameter("the_inputdate", the_inputdate) :
                new ObjectParameter("the_inputdate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<othert>("getoth", mergeOption, the_inputdateParameter);
        }
    
        public virtual ObjectResult<othert> gettheothers(string the_inputdate)
        {
            var the_inputdateParameter = the_inputdate != null ?
                new ObjectParameter("the_inputdate", the_inputdate) :
                new ObjectParameter("the_inputdate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<othert>("gettheothers", the_inputdateParameter);
        }
    
        public virtual ObjectResult<othert> gettheothers(string the_inputdate, MergeOption mergeOption)
        {
            var the_inputdateParameter = the_inputdate != null ?
                new ObjectParameter("the_inputdate", the_inputdate) :
                new ObjectParameter("the_inputdate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<othert>("gettheothers", mergeOption, the_inputdateParameter);
        }
    }
}
